parameters:
#    ml_service.example.class: Ml\ServiceBundle\Example

services:
    ml.session:
        class: Ml\libServices\SessionTested
    ml.reservation:
        class: Ml\libServices\ReservationTested
