ml_prestation_homepage:
    pattern: /prestation
    defaults: { _controller: MlPrestationBundle:Prestation:index }

ml_prestation_see_covoiturage:
    pattern: /prestation/see/covoiturage
    defaults: { _controller: MlPrestationBundle:Prestation:seeCovoiturage }

ml_prestation_add_covoiturage:
    pattern: /prestation/add/covoiturage
    defaults: { _controller: MlPrestationBundle:Prestation:addCovoiturage }

ml_prestation_delete_covoiturage:
    pattern: /prestation/delete/covoiturage
    defaults: { _controller: MlPrestationBundle:Prestation:deleteCovoiturage }
