ml_prestation_accueil:
    pattern: /presta
    defaults: { _controller: MlPrestationBundle:Prestation:index }

ml_prestation_see:
    pattern: /presta/see
    defaults: { _controller: MlPrestationBundle:Prestation:see }

ml_prestation_add:
    pattern: /presta/add
    defaults: { _controller: MlPrestationBundle:Prestation:index }

ml_prestation_delete:
    pattern: /presta/delete
    defaults: { _controller: MlPrestationBundle:Prestation:delete }
