parameters:
#    ml_prestation.example.class: Ml\PrestationBundle\Example

services:
#    ml_prestation.example:
#        class: %ml_prestation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
