ml_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MlUserBundle:Default:index }

ml_user_accueil:
    pattern: /accueil
    defaults: { _controller: MlUserBundle:User:index }

ml_user_see:
    pattern: /see
    defaults: { _controller: MlUserBundle:User:see }

ml_user_add:
    pattern: /add
    defaults: { _controller: MlUserBundle:User:add }

ml_user_delete:
    pattern: /delete
    defaults: { _controller: MlUserBundle:User:delete }
